[package]
name = "jay/rangefinder"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
knit = "sleitnick/knit@1.5.1"
component = "sleitnick/component@2.4.6"
trove = "sleitnick/trove@0.4.2"